name: gaussdb-web
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - fastapi=0.111.0
  - sqlalchemy=2.0.31
  - pydantic-settings=2.2.1
  - python-dotenv=1.0.1
  - requests=2.32.3
  - pytest=8.3.2
  - httpx=0.27.0
  - pip:
      - uvicorn[standard]==0.30.1
      - psycopg2-binary==2.9.9
      - pyspark==3.5.1
